
# Web API response statuses
DEFAULT_ERROR_MSG = 'Unknown Error'

STATUS_OK = 'OK'
STATUS_ERROR = 'ERROR'
STATUS_CLIENT_ERROR = 'CLIENT_ERROR'
STATUSES = [
	STATUS_OK,
	STATUS_ERROR,
	STATUS_CLIENT_ERROR
]