
# Web API response statuses
DEFAULT_ERROR_MSG = 'Unknown Error'

STATUS_OK = 'OK'
STATUS_ERROR = 'ERROR'
STATUS_CLIENT_ERROR = 'CLIENT_ERROR'
STATUSES = [
	STATUS_OK,
	STATUS_ERROR,
	STATUS_CLIENT_ERROR
]

MATCH_IN_PROGRESS = 'IN_PROGRESS'
MATCH_FAVORITE_WINS = 'FAVORITE'
MATCH_UNDERDOG_WINS = 'UNDERDOG'
MATCH_UNKNOWN_FAVORITE = 'UNKNOWN_FAVORITE'
MATCH_UNKNOWN_UNDERDOG = 'UNKNOWN_UNDERDOG'

MATCH_STATUSES = [
	MATCH_IN_PROGRESS,
	MATCH_FAVORITE_WINS,
	MATCH_UNDERDOG_WINS,
	MATCH_UNKNOWN_FAVORITE,
	MATCH_UNKNOWN_UNDERDOG,
]

MATCH_STATUS_TO_INT = {
	MATCH_IN_PROGRESS: 0,
	MATCH_FAVORITE_WINS: 1,
	MATCH_UNDERDOG_WINS: 2,
	MATCH_UNKNOWN_FAVORITE: 3,
	MATCH_UNKNOWN_UNDERDOG: 4
}

